/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package puzlecompuertaslogicas;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class VistaSimulador extends javax.swing.JFrame {
    private Usuario usuarioLogeado;
    private GeneradorDeNiveles motor = new GeneradorDeNiveles();
    private Usuario usuarioActual;
    private int compuertaOculta; 
    private Random randMisterio = new Random();
    private String respuestaTemporal = "";
    private int[] histCompuertasOcultasVisual = new int[50];
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VistaSimulador.class.getName());

    public VistaSimulador(Usuario usuarioLogeado) {
        initComponents();
        
        lblTextoA.setForeground(java.awt.Color.WHITE); // Entrada A
        lblTextoB.setForeground(java.awt.Color.WHITE); // Entrada B
        lblTextoC.setForeground(java.awt.Color.WHITE); // Entrada C
        lblTextoD.setForeground(java.awt.Color.WHITE); // Entrada D
        
        // 1. Vinculamos el usuario logueado a la interfaz
        this.usuarioActual = usuarioLogeado;
        
        // 2. Cargamos el progreso del usuario en el motor de manera limpia
        if (this.usuarioActual != null && this.motor != null) {
            int niv = usuarioActual.getNivelAlcanzado();
            this.motor.setNivelActual(niv);
            
            String[] nombresHist = usuarioActual.getHistNombreCompuertaActual();
            
            // --- VERIFICACIÓN DE NIVEL NUEVO O HISTORIAL VACÍO ---
            if (niv < 5 || nombresHist == null || niv >= nombresHist.length || nombresHist[niv] == null || nombresHist[niv].trim().isEmpty()) {
                
                // Si el nivel es nuevo o un tutorial, NO le pasamos los arrays viejos/vacíos al motor.
                // Forzamos al motor a generar un circuito completamente fresco y limpio.
                this.motor.generarCircuito();
                
            } else {
                // Si realmente hay datos guardados para este nivel, se los inyectamos de forma segura
                this.motor.setHistEntradaA(usuarioActual.getHistEntradaA());
                this.motor.setHistEntradaB(usuarioActual.getHistEntradaB());
                this.motor.setHistEntradaC(usuarioActual.getHistEntradaC());
                this.motor.setHistEntradaD(usuarioActual.getHistEntradaD());
                this.motor.setHistRespuestaEsperada(usuarioActual.getHistRespuestaEsperada()); 
                this.motor.setNivelYaRegistrado(usuarioActual.getNivelYaRegistrado());
                
                this.motor.restaurarCompuertasDesdeHistorial(
                    usuarioActual.getHistNombreCompuertaActual(),
                    usuarioActual.getHistNombreCompuertaAux1(),
                    usuarioActual.getHistNombreCompuertaAux2()
                );
                
                // Restauramos el historial visual de las casillas ocultas en la interfaz
                this.histCompuertasOcultasVisual = usuarioActual.getHistCompuertasOcultasVisual();
            }
            
            // 3. Ahora que el motor tiene compuertas válidas (ya sean nuevas o cargadas), calculamos la lógica
            this.motor.calcularResultadoInterno();
        }
        
        // Dejamos una sola llamada para evitar redundancia
        actualizarTablero();
        
        // Fondo general oscuro (Gris espacial / Negro azulado)
        this.getContentPane().setBackground(new java.awt.Color(33, 37, 41));
        
        // --- CONGELAMOS EL TAMAÑO DESDE EL NACIMIENTO DE LA VENTANA ---
        java.awt.Dimension tamInmutable = new java.awt.Dimension(140, 25);
        this.setSize(1000, 650); // Mantenemos el ancho cómodo de 1000 píxeles
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        
        lblCompuerta1.setPreferredSize(tamInmutable);
        lblCompuerta1.setMinimumSize(tamInmutable);
        lblCompuerta1.setMaximumSize(tamInmutable);
        
        lblCompuerta2.setPreferredSize(tamInmutable);
        lblCompuerta2.setMinimumSize(tamInmutable);
        lblCompuerta2.setMaximumSize(tamInmutable);
        
        lblCompuerta3.setPreferredSize(tamInmutable);
        lblCompuerta3.setMinimumSize(tamInmutable);
        lblCompuerta3.setMaximumSize(tamInmutable);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTextoA = new javax.swing.JLabel();
        lblTextoB = new javax.swing.JLabel();
        lblTextoC = new javax.swing.JLabel();
        lblTextoD = new javax.swing.JLabel();
        lblEstadoA = new javax.swing.JLabel();
        lblEstadoB = new javax.swing.JLabel();
        lblEstadoC = new javax.swing.JLabel();
        lblEstadoD = new javax.swing.JLabel();
        lblCompuerta1 = new javax.swing.JLabel();
        lblCompuerta2 = new javax.swing.JLabel();
        lblCompuerta3 = new javax.swing.JLabel();
        btnVerificar = new javax.swing.JButton();
        lblFocoSalida = new javax.swing.JLabel();
        lblNivel = new javax.swing.JLabel();
        lblIntentos = new javax.swing.JLabel();
        btnSiguiente = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnRespuestaAND = new javax.swing.JButton();
        btnRespuestaOR = new javax.swing.JButton();
        btnRespuestaXOR = new javax.swing.JButton();
        btnRespuestaNot = new javax.swing.JButton();
        cableA = new javax.swing.JSeparator();
        cableB = new javax.swing.JSeparator();
        cableD = new javax.swing.JSeparator();
        cableC = new javax.swing.JSeparator();
        cableSalida1 = new javax.swing.JSeparator();
        cableSalida2 = new javax.swing.JSeparator();
        cableFinal = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTextoA.setText("Entrada A");

        lblTextoB.setText("Entrada B");

        lblTextoC.setText("Entrada C");

        lblTextoD.setText("Entrada D");

        lblEstadoA.setText("jLabel5");
        lblEstadoA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstadoAMouseClicked(evt);
            }
        });

        lblEstadoB.setText("jLabel6");
        lblEstadoB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblEstadoBMouseClicked(evt);
            }
        });

        lblEstadoC.setText("jLabel7");

        lblEstadoD.setText("jLabel8");

        lblCompuerta1.setText("Compuerta 1");

        lblCompuerta2.setText("Compuerta 2");

        lblCompuerta3.setText("Compuerta 3");

        btnVerificar.setText("Verificar");
        btnVerificar.addActionListener(this::btnVerificarActionPerformed);

        lblFocoSalida.setText("Salida");

        lblNivel.setText("Nivel Actual");

        lblIntentos.setText("Intentos Restantes");

        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(this::btnSiguienteActionPerformed);

        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(this::btnAnteriorActionPerformed);

        btnRespuestaAND.setText("AND");
        btnRespuestaAND.addActionListener(this::btnRespuestaANDActionPerformed);

        btnRespuestaOR.setText("OR");
        btnRespuestaOR.addActionListener(this::btnRespuestaORActionPerformed);

        btnRespuestaXOR.setText("XOR");
        btnRespuestaXOR.addActionListener(this::btnRespuestaXORActionPerformed);

        btnRespuestaNot.setText("NOT");
        btnRespuestaNot.addActionListener(this::btnRespuestaNotActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVerificar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSiguiente))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIntentos)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lblTextoD)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblEstadoD))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblTextoB)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblEstadoB))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblTextoA)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(lblEstadoA)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGap(1, 1, 1)
                                                                .addComponent(cableA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(cableB, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblCompuerta1))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(cableD, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(cableC, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(lblCompuerta2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblTextoC)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lblEstadoC)
                                                .addGap(138, 138, 138)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(cableSalida2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                                            .addComponent(cableSalida1))
                                        .addGap(6, 6, 6)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCompuerta3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cableFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblFocoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnRespuestaAND)
                                            .addComponent(btnRespuestaOR)
                                            .addComponent(btnRespuestaXOR)
                                            .addComponent(btnRespuestaNot))
                                        .addGap(28, 28, 28))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(lblNivel)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblIntentos)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNivel)
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(lblTextoA)
                                                .addComponent(lblEstadoA))
                                            .addComponent(cableA, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblTextoB)
                                            .addComponent(lblEstadoB)
                                            .addComponent(cableB, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cableSalida1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCompuerta3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblFocoSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(lblCompuerta1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cableFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnRespuestaAND)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRespuestaOR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRespuestaXOR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRespuestaNot)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTextoC)
                                        .addComponent(lblEstadoC))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTextoD)
                                        .addComponent(lblEstadoD)))
                                .addComponent(lblCompuerta2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cableC, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cableD, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(cableSalida2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSiguiente)
                            .addComponent(btnVerificar)
                            .addComponent(btnAnterior))
                        .addGap(31, 31, 31))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerificarActionPerformed
        // TODO add your handling code here:
        // 1. Si está en niveles de tutorial (1 al 4), el botón verificar no hace falta
    if (motor.getNivelActual() <= 4) {
        JOptionPane.showMessageDialog(this, "En los niveles tutoriales debes interactuar con las entradas hasta activar la salida.", "Modo Tutorial", JOptionPane.INFORMATION_MESSAGE);
        return;
    }

    // 2. Si el alumno le dio a verificar sin elegir nada, le frenamos el carro
    if (respuestaTemporal.equals("")) {
        JOptionPane.showMessageDialog(this, "Por favor, selecciona una compuerta de la derecha (AND, OR, XOR, NOT) antes de verificar.", "Ninguna selección", JOptionPane.WARNING_MESSAGE);
        return;
    }

    boolean esCorrecto = motor.evaluarRespuestaMatematica(respuestaTemporal, compuertaOculta);
    
    // 5. Mandamos el veredicto directo a tu motor. 
    int estadoJuego = motor.verificar(esCorrecto);

    // 6. Evaluamos la respuesta del motor para mostrar el cartel correcto
    switch (estadoJuego) {
        case 0: // ¡ACERTÓ EL PUZLE!
            JOptionPane.showMessageDialog(this, "¡Excelente! Descubriste la compuerta oculta correctamente.", "Puzle Resuelto", JOptionPane.INFORMATION_MESSAGE);
            respuestaTemporal = ""; // Limpiamos la selección para el próximo nivel
            break;
            
        case 1: // FALLÓ, pero todavía le quedan intentos/vidas
            JOptionPane.showMessageDialog(this, "Incorrecto. Esa compuerta no genera la combinación de salida del circuito. ¡Intenta de nuevo!", "Respuesta Incorrecta", JOptionPane.WARNING_MESSAGE);
            // NOTA: No limpiamos respuestaTemporal para que el alumno vea qué puso y pueda cambiarla
            break;
            
        case 2: // SE QUEDÓ SIN INTENTOS (El motor ya habrá reseteado el puzle internamente)
            JOptionPane.showMessageDialog(this, "¡Te quedaste sin intentos! El circuito ha sido reiniciado con un nuevo puzle.", "Puzle Reiniciado", JOptionPane.ERROR_MESSAGE);
            respuestaTemporal = ""; // Limpiamos la selección porque el puzle cambió por completo
            break;
            
        case 3: // PENALIZACIÓN MÁXIMA (El motor lo bajó de nivel)
            JOptionPane.showMessageDialog(this, "¡Racha negativa! Has descendido de nivel para repasar los conceptos básicos.", "Descenso de Nivel", JOptionPane.ERROR_MESSAGE);
            respuestaTemporal = ""; // Limpiamos la selección
            break;
    }

    // 7. Refrescamos toda la pantalla con los nuevos datos (intentos, niveles, etc.)
    actualizarTablero();
    }//GEN-LAST:event_btnVerificarActionPerformed

    private void lblEstadoAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstadoAMouseClicked

        // Invertimos el valor de la entrada A en el motor
        motor.setEntradaA(!motor.isEntradaA());
        // Si estamos en niveles tutoriales (1 a 4), evaluamos dinámicamente si ya resolvió el tutorial
        motor.calcularResultadoInterno();
        //Bloqueo
        if (motor.getNivelActual() > 4) {
        return; 
        }
        if (motor.getNivelActual() <= 4) {
        // En el nivel 1 (AND), el objetivo es que ambas sean 1
        if (motor.getNivelActual() == 1 && motor.isEntradaA() && motor.isEntradaB()) {
            JOptionPane.showMessageDialog(this, "¡Excelente! Lograste activar la compuerta AND. Ya puedes avanzar.");
        }
    }
    // Refrescamos la pantalla para ver el cambio reflejado
    actualizarTablero();
    }//GEN-LAST:event_lblEstadoAMouseClicked

    private void lblEstadoBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEstadoBMouseClicked
        // TODO add your handling code here:
        motor.setEntradaB(!motor.isEntradaB());
        // 2. Obligamos al motor a recalcular el circuito
        motor.calcularResultadoInterno();
        // BLOQUEO
        if (motor.getNivelActual() > 4) {
        return; 
        }
    if (motor.getNivelActual() <= 4) {
        if (motor.getNivelActual() == 1 && motor.isEntradaA() && motor.isEntradaB()) {
            JOptionPane.showMessageDialog(this, "¡Excelente! Lograste activar la compuerta AND. Ya puedes avanzar.");
        }
    }
    actualizarTablero();
    }//GEN-LAST:event_lblEstadoBMouseClicked

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        // TODO add your handling code here:
       // Doble clic al botón Siguiente
    if (motor.getNivelActual() <= 4) {
        // --- VALIDACIONES OBLIGATORIAS PARA PASAR EL TUTORIAL (NIVELES 1 AL 4) ---
        boolean puedePasar = false;
        String mensajeError = "";

        if (motor.getNivelActual() == 1) {
            puedePasar = motor.isEntradaA() && motor.isEntradaB();
            mensajeError = "Para pasar el tutorial de la AND debes lograr que la salida sea 1 (Prender el foco).";
        } 
        else if (motor.getNivelActual() == 2) {
            puedePasar = motor.isEntradaA() || motor.isEntradaB();
            mensajeError = "Para pasar el tutorial de la OR debes lograr que la salida sea 1 (Prender el foco).";
        } 
        else if (motor.getNivelActual() == 3) {
            puedePasar = !motor.isEntradaA();
            mensajeError = "Para pasar el tutorial de la NOT debes lograr que la salida sea 1 (Invertir el 0 de la Entrada A).";
        } 
        else if (motor.getNivelActual() == 4) {
            puedePasar = motor.isEntradaA() ^ motor.isEntradaB();
            mensajeError = "Para pasar el tutorial de la XOR debes lograr que las entradas sean diferentes para prender el foco.";
        }

        // Evaluamos si el alumno resolvió el tutorial actual
        if (!puedePasar) {
            JOptionPane.showMessageDialog(this, mensajeError, "Tutorial incompleto", JOptionPane.WARNING_MESSAGE);
        } else {
            // Si lo resolvió correctamente, avanzamos de nivel en el motor
            motor.siguienteNivel();
            motor.calcularResultadoInterno(); 
            
            // --- CORRECCIÓN CRUCIAL: USAMOS usuarioActual ---
            if (this.usuarioActual != null) {
                this.usuarioActual.setNivelActual(motor.getNivelActual());
                if (motor.getNivelActual() > this.usuarioActual.getNivelMaximo()) {
                    this.usuarioActual.setNivelMaximo(motor.getNivelActual());
                }
                // Guardamos el objeto global real que maneja la pantalla
                Memorycard.guardarOActualizarUsuario(this.usuarioActual); 
            }
            
            // Limpieza de estados visuales para el nuevo nivel
            respuestaTemporal = "";             
            compuertaOculta = 0;                
            actualizarTablero();                
        }
    } 
    else {
        // --- LÓGICA NORMAL PARA NIVELES 5 EN ADELANTE (PUZLES OCULTOS) ---
        if (motor.siguienteNivel()) {
            motor.calcularResultadoInterno(); 
            
            // --- CORRECCIÓN CRUCIAL: USAMOS usuarioActual ---
            if (this.usuarioActual != null) {
                this.usuarioActual.setNivelActual(motor.getNivelActual());
                if (motor.getNivelActual() > this.usuarioActual.getNivelMaximo()) {
                    this.usuarioActual.setNivelMaximo(motor.getNivelActual());
                }
                // Guardamos el progreso en el archivo
                Memorycard.guardarOActualizarUsuario(this.usuarioActual); 
            }
            
            // Limpieza de estados visuales
            respuestaTemporal = "";             
            compuertaOculta = 0;                
            actualizarTablero();                
        } else {
            JOptionPane.showMessageDialog(this, "Debes resolver el puzle actual y darle a 'Verificar' antes de poder avanzar.", "Nivel Bloqueado", JOptionPane.WARNING_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnRespuestaANDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaANDActionPerformed
        // TODO add your handling code here:
                                                    
        respuestaTemporal = "AND";
        actualizarTablero();
        
    }//GEN-LAST:event_btnRespuestaANDActionPerformed

    private void btnRespuestaORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaORActionPerformed
        // TODO add your handling code here:
        respuestaTemporal = "OR";
       actualizarTablero();
    }//GEN-LAST:event_btnRespuestaORActionPerformed

    private void btnRespuestaXORActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaXORActionPerformed
        // TODO add your handling code here:
        respuestaTemporal = "XOR";
        actualizarTablero();
    }//GEN-LAST:event_btnRespuestaXORActionPerformed

    private void btnRespuestaNotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespuestaNotActionPerformed
        // TODO add your handling code here:
        respuestaTemporal = "NOT";
        actualizarTablero();
    }//GEN-LAST:event_btnRespuestaNotActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        // TODO add your handling code here:
        // 1. Le pedimos al motor que intente retroceder un nivel
    if (motor.anteriorNivel()) {
        
        // --- LIMPIEZA Y RESTAURACIÓN DE ESTADOS VISUALES ---
        // Vaciamos la respuesta que el usuario tenía escrita en el nivel avanzado
        respuestaTemporal = "";             
        
        // Seteamos en 0 para obligar a que el método actualizarTablero() lea la 
        // posición fija histórica de este nivel al que estamos regresando
        compuertaOculta = 0;               
        
        // 2. Refrescamos la pantalla para dibujar el circuito recuperado del historial
        actualizarTablero();                
        
    } else {
        // Si anteriorNivel() devuelve false es porque ya estábamos en el Nivel 1
        JOptionPane.showMessageDialog(this, "Ya estás en el primer nivel (Tutorial AND).", "Inicio del juego", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnRespuestaAND;
    private javax.swing.JButton btnRespuestaNot;
    private javax.swing.JButton btnRespuestaOR;
    private javax.swing.JButton btnRespuestaXOR;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JButton btnVerificar;
    private javax.swing.JSeparator cableA;
    private javax.swing.JSeparator cableB;
    private javax.swing.JSeparator cableC;
    private javax.swing.JSeparator cableD;
    private javax.swing.JSeparator cableFinal;
    private javax.swing.JSeparator cableSalida1;
    private javax.swing.JSeparator cableSalida2;
    private javax.swing.JLabel lblCompuerta1;
    private javax.swing.JLabel lblCompuerta2;
    private javax.swing.JLabel lblCompuerta3;
    private javax.swing.JLabel lblEstadoA;
    private javax.swing.JLabel lblEstadoB;
    private javax.swing.JLabel lblEstadoC;
    private javax.swing.JLabel lblEstadoD;
    private javax.swing.JLabel lblFocoSalida;
    private javax.swing.JLabel lblIntentos;
    private javax.swing.JLabel lblNivel;
    private javax.swing.JLabel lblTextoA;
    private javax.swing.JLabel lblTextoB;
    private javax.swing.JLabel lblTextoC;
    private javax.swing.JLabel lblTextoD;
    // End of variables declaration//GEN-END:variables

private void actualizarTablero() {
    // --- PALETA DE COLORES MODO OSCURO / TECNOLÓGICO ---
    java.awt.Color colorON = new java.awt.Color(46, 204, 113);       // Verde Eléctrico (1)
    java.awt.Color colorOFF = new java.awt.Color(149, 165, 166);     // Gris Eléctrico Apagado (0)
    java.awt.Color colorFocoON = new java.awt.Color(241, 196, 15);   // Amarillo Foco encendido
    java.awt.Color colorFocoOFF = new java.awt.Color(44, 62, 80);    // Gris Oscuro Foco apagado
    java.awt.Color fondoCajaVisible = new java.awt.Color(52, 73, 94); // Azul Grisáceo para compuertas reveladas
    java.awt.Color colorMisterio = new java.awt.Color(155, 89, 182);   // Morado Tecnológico para la oculta

    // Oculta el botón verificar si está en los niveles tutoriales (1 al 4)
    if (motor.getNivelActual() <= 4) {
        btnVerificar.setVisible(false);
    } else {
        btnVerificar.setVisible(true);
    }
    
    // ===================================================
    // 1. MARCADOR DE CONTROL (NIVEL e INTENTOS)
    // ===================================================
    lblNivel.setText("Nivel Actual: " + motor.getNivelActual());
    lblNivel.setForeground(java.awt.Color.WHITE);
    
    lblIntentos.setText("Intentos Restantes: " + motor.getIntentosRestantes());
    if (motor.getIntentosRestantes() <= 1) {
        lblIntentos.setForeground(new java.awt.Color(231, 76, 60)); // Rojo peligro si le queda 1 vida
    } else {
        lblIntentos.setForeground(colorON);
    }
    
    // ===================================================
    // 2. ESTADOS DE LAS ENTRADAS (A, B, C, D) + COLORES
    // ===================================================
    // Asegurar contraste de las etiquetas de texto principales
    lblEstadoA.setForeground(java.awt.Color.WHITE);
    lblEstadoB.setForeground(java.awt.Color.WHITE);
    lblEstadoC.setForeground(java.awt.Color.WHITE);
    lblEstadoD.setForeground(java.awt.Color.WHITE);
    
    boolean estadoA = motor.isEntradaA();
    lblEstadoA.setText(estadoA ? "1 (ON)" : "0 (OFF)");
    lblEstadoA.setBackground(estadoA ? colorON : colorOFF);
    lblEstadoA.setOpaque(true);

    boolean estadoB = motor.isEntradaB();
    lblEstadoB.setText(estadoB ? "1 (ON)" : "0 (OFF)");
    lblEstadoB.setBackground(estadoB ? colorON : colorOFF);
    lblEstadoB.setOpaque(true);

    boolean estadoC = motor.isEntradaC();
    lblEstadoC.setText(estadoC ? "1 (ON)" : "0 (OFF)");
    lblEstadoC.setBackground(estadoC ? colorON : colorOFF);
    lblEstadoC.setOpaque(true);

    boolean estadoD = motor.isEntradaD();
    lblEstadoD.setText(estadoD ? "1 (ON)" : "0 (OFF)");
    lblEstadoD.setBackground(estadoD ? colorON : colorOFF);
    lblEstadoD.setOpaque(true);
    
    // ===================================================
    // 3. CONTROL DE VISIBILIDAD DE ENTRADAS Y COMPUERTAS
    // ===================================================
    if (motor.getNivelActual() == 3) { 
        // Nivel de la NOT: Solo mostramos la Entrada A
        lblEstadoA.setVisible(true);
        lblEstadoB.setVisible(false); 
        lblEstadoC.setVisible(false); 
        lblEstadoD.setVisible(false);
        lblCompuerta2.setVisible(false); // Ocultamos la de abajo
    } 
    else if (motor.getNivelActual() == 1 || motor.getNivelActual() == 2 || motor.getNivelActual() == 4) {
        // Otros niveles tutoriales de 2 entradas: Mostramos solo A y B
        lblEstadoA.setVisible(true);
        lblEstadoB.setVisible(true);
        lblEstadoC.setVisible(false);
        lblEstadoD.setVisible(false);
        lblCompuerta2.setVisible(false); // Ocultamos la de abajo
    } 
    else if (motor.getNivelActual() == 5 || motor.getNivelActual() == 6) {
        // Estructura en cascada (3 entradas): Usamos A, B y C. Ocultamos D y la Compuerta 2 (abajo).
        lblEstadoA.setVisible(true);
        lblEstadoC.setVisible(true);
        lblEstadoD.setVisible(false);    
        lblCompuerta2.setVisible(false); // ¡La de abajo desaparece físicamente!
        
        if (motor.getCompuertaActual() != null && "NOT".equalsIgnoreCase(motor.getCompuertaActual().getNombre())) {
            lblEstadoB.setVisible(false);
        } else {
            lblEstadoB.setVisible(true);
        }
    } 
    else {
        // Niveles avanzados de árbol (4 entradas): Mostramos todo
        lblEstadoA.setVisible(true);
        lblEstadoC.setVisible(true);
        lblCompuerta2.setVisible(true);  
        
        if (motor.getCompuertaActual() != null && "NOT".equalsIgnoreCase(motor.getCompuertaActual().getNombre())) {
            lblEstadoB.setVisible(false);
        } else {
            lblEstadoB.setVisible(true);
        }

        if (motor.getCompuertaAux1() != null && "NOT".equalsIgnoreCase(motor.getCompuertaAux1().getNombre())) {
            lblEstadoD.setVisible(false);
        } else {
            lblEstadoD.setVisible(true);
        }
    }

    // ===================================================
    // 4. ACTUALIZACIÓN AUTOMÁTICA DEL CABLEADO COBRA VIDA
    // ===================================================
    boolean salidaFinal = motor.isRespuestaEsperada();
    try {
        // Cables directos de las entradas
        if (findComponent("cableA") != null) getComponentByName("cableA").setForeground(estadoA ? colorON : colorOFF);
        if (findComponent("cableB") != null) getComponentByName("cableB").setForeground(estadoB ? colorON : colorOFF);
        if (findComponent("cableC") != null) getComponentByName("cableC").setForeground(estadoC ? colorON : colorOFF);
        if (findComponent("cableD") != null) getComponentByName("cableD").setForeground(estadoD ? colorON : colorOFF);
        
        // --- CABLES INTERMEDIOS Y FINALES ---
        // Cable Salida 1: Conecta la salida de la Compuerta 1 (Arriba) hacia adelante
        boolean señalSalida1 = false;
        if (motor.getCompuertaActual() != null) {
            String tipoComp1 = motor.getCompuertaActual().getNombre().toUpperCase().trim();
            switch (tipoComp1) {
                case "AND": señalSalida1 = estadoA && estadoB; break;
                case "OR":  señalSalida1 = estadoA || estadoB; break;
                case "XOR": señalSalida1 = estadoA ^ estadoB;  break;
                case "NOT": señalSalida1 = !estadoA;           break;
                default:    señalSalida1 = false;
            }
        }
        if (findComponent("cableSalida1") != null) {
            getComponentByName("cableSalida1").setForeground(señalSalida1 ? colorON : colorOFF);
        }
        
        // Cable Salida 2: Conecta la salida de la Compuerta 2 (Abajo) hacia adelante
        boolean señalSalida2 = false;
        if (motor.getCompuertaAux1() != null) {
            String tipoComp2 = motor.getCompuertaAux1().getNombre().toUpperCase().trim();
            switch (tipoComp2) {
                case "AND": señalSalida2 = estadoC && estadoD; break;
                case "OR":  señalSalida2 = estadoC || estadoD; break;
                case "XOR": señalSalida2 = estadoC ^ estadoD;  break;
                case "NOT": señalSalida2 = !estadoC;           break;
                default:    señalSalida2 = false;
            }
        }
        if (findComponent("cableSalida2") != null) {
            getComponentByName("cableSalida2").setForeground(señalSalida2 ? colorON : colorOFF);
        }
        // Cable Final: Conecta la compuerta final / misteriosa directo con el Foco de Salida
        if (findComponent("cableFinal") != null) {
            getComponentByName("cableFinal").setForeground(salidaFinal ? colorON : colorOFF);
        }
    } catch (Exception e) {
        // Silenciamos cualquier error reflectivo para que el juego siga corriendo sin problemas
    }
    
    // ===================================================
    // 5. EL FOCO DE SALIDA (ESTADO FINAL ENERGIZADO)
    // ===================================================
    // Fijamos tamaño robusto para evitar que Swing recorte el texto
    java.awt.Dimension tamFoco = new java.awt.Dimension(135, 30);
    lblFocoSalida.setPreferredSize(tamFoco);
    lblFocoSalida.setMinimumSize(tamFoco);
    lblFocoSalida.setMaximumSize(tamFoco);
    lblFocoSalida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lblFocoSalida.setFont(new java.awt.Font("SansSerif", java.awt.Font.BOLD, 12));
    
    if (salidaFinal) {
        lblFocoSalida.setText(" 💡 ");
        lblFocoSalida.setBackground(colorFocoON);
        lblFocoSalida.setForeground(java.awt.Color.BLACK);
    } else {
        lblFocoSalida.setText(" ⚫ ");
        lblFocoSalida.setBackground(colorFocoOFF);
        lblFocoSalida.setForeground(java.awt.Color.WHITE);
    }
    lblFocoSalida.setOpaque(true);

    // ===================================================
    // 6. LÓGICA DE RENDICIÓN VISUAL RÍGIDA DE COMPUERTAS
    // ===================================================
    int lvlClave = motor.getNivelActual();

    if (compuertaOculta == 0) {
        if (histCompuertasOcultasVisual[lvlClave] != 0) {
            compuertaOculta = histCompuertasOcultasVisual[lvlClave];
        } else {
            if (lvlClave == 5 || lvlClave == 6) {
                compuertaOculta = 3; 
            } else {
                compuertaOculta = randMisterio.nextInt(3) + 1; 
            }
            histCompuertasOcultasVisual[lvlClave] = compuertaOculta;
        }
    }

    // --- RENDERIZADO SEGÚN EL TIPO DE NIVEL ---
    if (motor.getNivelActual() <= 4) {
        lblCompuerta1.setText(motor.getCompuertaActual() != null ? motor.getCompuertaActual().getNombre() : "---");
        lblCompuerta1.setBackground(fondoCajaVisible);
        lblCompuerta1.setForeground(java.awt.Color.WHITE);
        lblCompuerta1.setOpaque(true);
        
        lblCompuerta2.setText("---");
        lblCompuerta2.setBackground(colorFocoOFF);
        lblCompuerta2.setOpaque(true);
        
        lblCompuerta3.setText("---");
        lblCompuerta3.setBackground(colorFocoOFF);
        lblCompuerta3.setOpaque(true);
        
        lblCompuerta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    } 
    else {
        // --- PREPARAMOS EL TEXTO DEL MISTERIO ---
        String textoMisterio = "[ ? ] MISTERIO";
        if (!respuestaTemporal.equals("")) {
            textoMisterio = "[ " + respuestaTemporal + " ] MISTERIO";
        }

        // --- TAMAÑOS INMUTABLES PARA EVITAR DESFASES ---
        java.awt.Dimension tamFijo = new java.awt.Dimension(140, 25);
        
        lblCompuerta1.setPreferredSize(tamFijo);
        lblCompuerta1.setMinimumSize(tamFijo);
        lblCompuerta1.setMaximumSize(tamFijo);
        lblCompuerta1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompuerta1.setOpaque(true);

        lblCompuerta2.setPreferredSize(tamFijo);
        lblCompuerta2.setMinimumSize(tamFijo);
        lblCompuerta2.setMaximumSize(tamFijo);
        lblCompuerta2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompuerta2.setOpaque(true);

        lblCompuerta3.setPreferredSize(tamFijo);
        lblCompuerta3.setMinimumSize(tamFijo);
        lblCompuerta3.setMaximumSize(tamFijo);
        lblCompuerta3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCompuerta3.setOpaque(true);

        // --- DIBUJADO ESTRICTO DE TEXTOS Y COLORES ---
        
        // Compuerta 1 (Arriba)
        if (compuertaOculta == 1) {
            lblCompuerta1.setText(textoMisterio);
            lblCompuerta1.setBackground(colorMisterio);
            lblCompuerta1.setForeground(java.awt.Color.WHITE);
        } else {
            lblCompuerta1.setText(motor.getCompuertaActual() != null ? motor.getCompuertaActual().getNombre() : "---");
            lblCompuerta1.setBackground(fondoCajaVisible);
            lblCompuerta1.setForeground(java.awt.Color.WHITE);
        }

        // Compuerta 2 (Abajo - Solo activa en niveles de árbol)
        if (compuertaOculta == 2) {
            lblCompuerta2.setText(textoMisterio);
            lblCompuerta2.setBackground(colorMisterio);
            lblCompuerta2.setForeground(java.awt.Color.WHITE);
        } else {
            lblCompuerta2.setText(motor.getCompuertaAux1() != null ? motor.getCompuertaAux1().getNombre() : "---");
            lblCompuerta2.setBackground(fondoCajaVisible);
            lblCompuerta2.setForeground(java.awt.Color.WHITE);
        }

        // Compuerta 3 (Derecha - Unión final)
        if (compuertaOculta == 3) {
            lblCompuerta3.setText(textoMisterio);
            lblCompuerta3.setBackground(colorMisterio);
            lblCompuerta3.setForeground(java.awt.Color.WHITE);
        } else {
            if (motor.getNivelActual() >= 7) {
                lblCompuerta3.setText(motor.getCompuertaAux2() != null ? motor.getCompuertaAux2().getNombre() : "---");
            } else {
                lblCompuerta3.setText(motor.getCompuertaAux1() != null ? motor.getCompuertaAux1().getNombre() : "---");
            }
            lblCompuerta3.setBackground(fondoCajaVisible);
            lblCompuerta3.setForeground(java.awt.Color.WHITE);
        }
    }
}

// ===================================================
// 7. MÉTODOS REFLECTIVOS AUXILIARES (PROTECCIÓN ANTI-CAÍDAS)
// ===================================================
private javax.swing.JComponent findComponent(String name) {
    try {
        java.lang.reflect.Field field = this.getClass().getDeclaredField(name);
        field.setAccessible(true);
        return (javax.swing.JComponent) field.get(this);
    } catch (Exception e) {
        return null;
    }
}

private javax.swing.JComponent getComponentByName(String name) throws Exception {
    java.lang.reflect.Field field = this.getClass().getDeclaredField(name);
    field.setAccessible(true);
    return (javax.swing.JComponent) field.get(this);
}}